{% set name = "jupyterlite-xeus" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlite_xeus-{{ version }}.tar.gz
  sha256: bfe0ef75a3562379ea456a155464844267b7109631b1d0523a1f592d86af54cf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - jupyterlab >=3,<4
    - empack >=3.1,<4
    - hatchling
    - hatch-jupyter-builder
    - hatch-nodejs-version
  run:
    - python >=3.8
    - empack >=3.1,<4
    - traitlets
    - jupyterlite-core >=0.2,<0.3
    - pyyaml
    - requests

test:
  imports:
    - jupyterlite_xeus
  requires:
    - pip
  commands:
    - pip check
    - test -f ${PREFIX}/share/jupyter/labextensions/@jupyterlite/xeus/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupyterlite/xeus\\package.json (exit 1)          # [win]

about:
  home: https://github.com/jupyterlite/xeus
  summary: JupyterLite loader for Xeus kernels
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/jupyterlite/xeus

extra:
  recipe-maintainers:
    - martinRenou
